fos_oauth_server:
  db_driver: orm
  client_class:        App\Entity\Security\Client
  access_token_class:  App\Entity\Security\AccessToken
  refresh_token_class: App\Entity\Security\RefreshToken
  auth_code_class:     App\Entity\Security\AuthCode
