jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            DTO:
                namespace_prefix: "App\\DTO"
                path: "%kernel.project_dir%/config/serializer/DTO"
            BadRequest:
                namespace_prefix: "App\\DTO\\BadRequest"
                path: "%kernel.project_dir%/config/serializer/DTO/BadRequest"
