security:
  encoders:
    App\Entity\Security\User:
      algorithm: bcrypt
      cost: 12

  providers:
    player_provider:
      entity:
        class: App\Entity\Security\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern:    ^/v\d+
      stateless:  true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    app:
      pattern: ^/
      security: false

  access_control:
    - { path: ^/doc, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
    - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
