version: "2"
services:
    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - test-network

    php:
        build: ./docker/php/
        container_name: php
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
            - ./vendor:/var/www/app/vendor:cached
        environment:
            TIMEZONE: ${TIMEZONE}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            - mysql
        networks:
            - test-network
    nginx:
        image: nginx:1.11
        container_name: nginx
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 81:80
        networks:
            - test-network
networks:
    test-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
