App\Entity\CartItem:
  properties:
    product:
      - NotNull: ~
    quantity:
      - NotNull: ~
      - Type: integer
      - GreaterThan: 0

App\Entity\Product:
  properties:
    name:
      - Type: string
      - Length:
          min: 1
          max: 255
      - NotBlank:
          groups:
            - Create
    price:
      - NotNull:
          groups: Create
      - Valid: ~

App\DTO\Product\ProductCriteria:
  properties:
    name:
      - Type: string
      - Length:
          max: 125
