App\DTO\Page:
  exclusion_policy: ALL
  properties:
    number:
      expose: true
      type: integer
      serialized_name: page
    total:
      expose: true
      type: integer
    items:
      expose: true
      type: array